Repository Tailormap/tailormap-api, pull requests merged in 2021-12, with the labels that each got.

#4 read version from properties and add integration test
  .github/workflows/ubuntu-maven.yml
  .reuse/dep5
  pom.xml
  src/main/java/nl/b3p/tailormap/api/controller/VersionController.java
  src/main/resources/application.properties
  src/site/site.xml
  src/test/java/nl/b3p/tailormap/api/controller/VersionControllerIntegrationTest.java
Labels: infrastucture, dependency

#2 [HTM-25] initial OpenAPI contract for tailormap-api
  src/main/resources/model.yaml
  src/main/resources/statusresponses.yaml
  src/main/resources/tailormap-api.yaml
Labels: enhancement

#6 [QA] validate javadoc
  .github/workflows/qa.yml
  pom.xml
  src/main/java/nl/b3p/tailormap/api/controller/VersionController.java
Labels: infrastucture

#5 [HTM-35] Verplaats docker image hosting naar github packages
  .github/maven-settings.xml
  .github/workflows/ubuntu-maven.yml
  README.md
  pom.xml
Labels: documentation, enhancement, infrastucture

#7 [HTM-38] Add database connectivity for Tailormap API
  .github/workflows/macos-maven.yml
  .github/workflows/ubuntu-maven.yml
  .github/workflows/windows-maven.yml
  Dockerfile
  README.md
  pom.xml
  src/main/java/nl/b3p/tailormap/api/JPAConfiguration.java
  src/main/java/nl/b3p/tailormap/api/controller/AppController.java
  src/main/java/nl/b3p/tailormap/api/controller/VersionController.java
  src/main/java/nl/b3p/tailormap/api/repository/MetadataRepository.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/tailormap-api.yaml
  src/test/java/nl/b3p/tailormap/api/HSQLDBTestProfileJPAConfiguration.java
  src/test/java/nl/b3p/tailormap/api/TailormapApiApplicationTests.java
  src/test/java/nl/b3p/tailormap/api/controller/VersionControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/repository/MetadataRepositoryIntegrationTest.java
  src/test/resources/application.properties
Labels: enhancement

#9 [HTM-11] Make the CoordinateReferenceSystem also carry the PROJ4 definition as well as (optional) area of validity
  src/main/resources/model.yaml
Labels: enhancement

#11 [HTM-66] Add FilterRegistrationBean to handle proxy headers
  src/main/java/nl/b3p/tailormap/api/FilteringConfig.java
Labels: enhancement

#12 Changed api_version to apiVersion since camelCase is used everywhere
  src/main/java/nl/b3p/tailormap/api/controller/AppController.java
  src/main/java/nl/b3p/tailormap/api/controller/VersionController.java
  src/main/resources/tailormap-api.yaml
Labels: bug

#10 [HTM-61] Add a healthcheck to obtain Tailormap versions from the database and environment
  src/main/java/nl/b3p/tailormap/api/health/TailormapHealthIndicator.java
  src/main/resources/application.properties
  src/test/java/nl/b3p/tailormap/api/health/TailormapHealthIndicatorDisabledTest.java
  src/test/java/nl/b3p/tailormap/api/health/TailormapHealthIndicatorEnabledIntegrationTest.java
  src/test/resources/application.properties
Labels: enhancement

#16 [HTM-67] Generate OpenAPI model Java classes
  .github/workflows/ubuntu-maven.yml
  pom.xml
  src/main/resources/model.yaml
  src/main/resources/tailormap-api.yaml
Labels: enhancement

#22 Improve integration testing
  pom.xml
  src/main/java/nl/b3p/tailormap/api/controller/AppController.java
  src/main/java/nl/b3p/tailormap/api/controller/VersionController.java
  src/main/resources/application.properties
  src/main/resources/tailormap-api.yaml
  src/test/java/nl/b3p/tailormap/api/HSQLDBTestProfileJPAConfiguration.java
  src/test/java/nl/b3p/tailormap/api/controller/VersionControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/health/TailormapHealthIndicatorEnabledIntegrationTest.java
  src/test/resources/application.properties
Labels: bug, enhancement, infrastucture

#18 [HTM-68] `app` endpoint
  src/main/java/nl/b3p/tailormap/api/controller/AppController.java
  src/main/java/nl/b3p/tailormap/api/repository/ApplicationRepository.java
  src/main/resources/tailormap-api.yaml
  src/test/java/nl/b3p/tailormap/api/TailormapApiApplicationTests.java
  src/test/java/nl/b3p/tailormap/api/controller/AppControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/AppControllerTest.java
  src/test/java/nl/b3p/tailormap/api/health/TailormapHealthIndicatorDisabledTest.java
  src/test/java/nl/b3p/tailormap/api/repository/ApplicationRepositoryIntegrationTest.java
Labels: enhancement

#23 [HTM-69] Add `map/{appid}` endpoint
  pom.xml
  src/main/java/nl/b3p/tailormap/api/controller/MapController.java
  src/main/resources/model.yaml
  src/main/resources/tailormap-api.yaml
  src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/MapControllerTest.java
Labels: enhancement

#24 [HTM-71] Add LayersController for layers/{appid}
  src/main/java/nl/b3p/tailormap/api/controller/LayersController.java
  src/test/java/nl/b3p/tailormap/api/controller/LayersControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/LayersControllerTest.java
Labels: enhancement

#27 [HTM-70] initial components endpoint
  src/main/java/nl/b3p/tailormap/api/controller/ComponentsController.java
  src/test/java/nl/b3p/tailormap/api/controller/ComponentsControllerIntegrationTest.java
Labels: enhancement
