Repository Tailormap/tailormap-api, pull requests merged in 2022-11, with the labels that each got.

#226 Dependency updates
  pom.xml
Labels: dependency

#231 Bump hibernate.version from 5.6.12.Final to 5.6.13.Final
  pom.xml
Labels: dependency

#234 Bump hibernate.version from 5.6.13.Final to 5.6.14.Final
  pom.xml
Labels: dependency

#223 Improve authorization checks
  src/main/java/nl/b3p/tailormap/api/controller/AppController.java
  src/main/java/nl/b3p/tailormap/api/controller/ComponentsController.java
  src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
  src/main/java/nl/b3p/tailormap/api/controller/MapController.java
  src/main/java/nl/b3p/tailormap/api/controller/UniqueValuesController.java
  src/main/java/nl/b3p/tailormap/api/security/AuthUtil.java
  src/main/java/nl/b3p/tailormap/api/security/AuthorizationService.java
  src/test/java/nl/b3p/tailormap/api/controller/AppControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/ComponentsControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/MapControllerPostgresIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/MapControllerTest.java
  src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerPostgresIntegrationTest.java
Labels: enhancement

#235 Bump jackson-bom.version from 2.14.0-rc3 to 2.14.0
  pom.xml
Labels: dependency

#246 [HTM-581] Fix NPE when service layer missing
  src/main/java/nl/b3p/tailormap/api/controller/MapController.java
Labels: bug

#252 Bump jackson-bom.version from 2.14.0 to 2.14.1
  pom.xml
Labels: dependency

#253 [HTM-583] Add LayerDescriptionController
  src/main/java/nl/b3p/tailormap/api/controller/LayerDescriptionController.java
  src/main/resources/model.yaml
  src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerPostgresIntegrationTest.java
Labels: enhancement
