Repository Tailormap/tailormap-api, pull requests merged in 2022-10, with the labels that each got.

#212 [HTM-466] enable Sentry
  pom.xml
  src/main/resources/application.properties
  src/main/resources/spy.properties
Labels: enhancement, hacktoberfest-accepted

#215 [HTM-527] set-up multi-arch builds
  Dockerfile
  README.md
  pom.xml
Labels: documentation, enhancement, infrastucture, hacktoberfest-accepted

#221 Bump tailormap-persistence to 10.1-SNAPSHOT
  pom.xml
Labels: dependency

#225 Update ubuntu packages before upgrade
  Dockerfile
Labels: infrastucture, dependency, security
