Repository Tailormap/tailormap-api, pull requests merged in 2022-02, with the labels that each got.

#52 Set-up Trivy security scanner
  .github/workflows/owasp-dependency-check.yml
  .github/workflows/trivy.yml
  pom.xml
Labels: infrastucture, dependency

#54 [HTM-206] Check login required on application
  pom.xml
  src/main/java/nl/b3p/tailormap/api/controller/AppController.java
  src/main/java/nl/b3p/tailormap/api/controller/ComponentsController.java
  src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
  src/main/java/nl/b3p/tailormap/api/controller/LayersController.java
  src/main/java/nl/b3p/tailormap/api/controller/MapController.java
  src/main/java/nl/b3p/tailormap/api/repository/ApplicationRepository.java
  src/main/java/nl/b3p/tailormap/api/security/AuthUtil.java
  src/main/resources/tailormap-api.yaml
  src/test/java/nl/b3p/tailormap/api/TestSecurityConfig.java
  src/test/java/nl/b3p/tailormap/api/controller/AppControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/ComponentsControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/LayersControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/health/TailormapHealthIndicatorDisabledTest.java
Labels: enhancement

#57 [HTM-205] Change API url design
  src/main/java/nl/b3p/tailormap/api/controller/ComponentsController.java
  src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
  src/main/java/nl/b3p/tailormap/api/controller/LayersController.java
  src/main/java/nl/b3p/tailormap/api/controller/MapController.java
  src/main/resources/tailormap-api.yaml
  src/test/java/nl/b3p/tailormap/api/controller/ComponentsControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/LayersControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java
Labels: enhancement

#53 [HTM-118][HTM-207][HTM-208] Add security
  src/main/java/nl/b3p/tailormap/api/repository/UserRepository.java
  src/main/java/nl/b3p/tailormap/api/security/AuthUtil.java
  src/main/java/nl/b3p/tailormap/api/security/SecurityConfig.java
  src/main/java/nl/b3p/tailormap/api/security/StartupAdminAccountCreator.java
  src/main/java/nl/b3p/tailormap/api/security/TailormapUserDetails.java
  src/main/java/nl/b3p/tailormap/api/security/TailormapUserDetailsService.java
  src/main/resources/application.properties
  src/main/resources/tailormap-api.yaml
  src/test/java/nl/b3p/tailormap/api/controller/AppControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/ComponentsControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/LayersControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/MapControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/security/TailormapUserDetailsServiceTest.java
  src/test/java/nl/b3p/tailormap/api/security/TestSecurityConfig.java
Labels: enhancement

#58 Check if there is only one `gt-main` and only one `gt-epsg` jar in the runnable jar
  src/test/java/nl/b3p/tailormap/api/ValidateGeoToolsInArtifactIntegrationTest.java
Labels: enhancement, dependency
