Repository Tailormap/tailormap-api, pull requests merged in 2023-07, with the labels that each got.

#518 Update front controller URLs
  src/main/java/nl/b3p/tailormap/api/configuration/base/FrontController.java
Labels: bug

#519 reactivate ViewerControllerPostgresIntegrationTest#should_contain_description()
  src/test/java/nl/b3p/tailormap/api/controller/ViewerControllerPostgresIntegrationTest.java
Labels: enhancement, infrastucture

#516 [HTM-849] Send friendly error messages when loading service fails
  src/main/java/nl/b3p/tailormap/api/controller/admin/AdminRepositoryRestExceptionHandler.java
  src/main/java/nl/b3p/tailormap/api/controller/admin/GeoServiceAdminController.java
  src/main/java/nl/b3p/tailormap/api/geotools/ResponseTeeingHTTPClient.java
  src/main/java/nl/b3p/tailormap/api/geotools/WMSServiceExceptionUtil.java
  src/main/java/nl/b3p/tailormap/api/persistence/GeoService.java
  src/main/java/nl/b3p/tailormap/api/persistence/helper/GeoServiceHelper.java
  src/main/java/nl/b3p/tailormap/api/repository/events/GeoServiceEventHandler.java
  src/main/java/nl/b3p/tailormap/api/repository/validation/GeoServiceValidator.java
  src/main/java/nl/b3p/tailormap/api/repository/validation/ValidationConfiguration.java
  src/main/resources/openapi/persistence-schemas.yaml
  src/test/java/nl/b3p/tailormap/api/controller/admin/GeoServiceAdminControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/admin/JSR303ValidationIntegrationTest.java
  src/test/resources/wms/service_exception_1_0_0.xml
  src/test/resources/wms/service_exception_1_3_0.xml
Labels: enhancement

#517 [HTM-835] Make `edit/feature` application-CRS transparent
  src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/nl/b3p/tailormap/api/controller/EditFeatureController.java
  src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
  src/main/java/nl/b3p/tailormap/api/geotools/TransformationUtil.java
  src/main/java/nl/b3p/tailormap/api/geotools/processing/GeometryProcessor.java
  src/main/resources/openapi/viewer-api.yaml
  src/test/java/nl/b3p/tailormap/api/controller/EditFeatureControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/ViewerControllerPostgresIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/geotools/processing/GeometryProcessorTest.java
  src/test/resources/StaticTestData.properties
Labels: enhancement

#523 [HTM-874] factor out the superfluous `crs` parameter from the `/features` endpoint
  src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
  src/main/java/nl/b3p/tailormap/api/geotools/TransformationUtil.java
  src/main/resources/openapi/viewer-api.yaml
  src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/GeoServiceProxyControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerReConfiguredIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/ViewerControllerIntegrationTest.java
Labels: bug

#527 [HTM-879] Discover and produce the primary key of a feature type
  src/main/java/nl/b3p/tailormap/api/controller/LayerDescriptionController.java
  src/main/java/nl/b3p/tailormap/api/geotools/featuresources/FeatureSourceHelper.java
  src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerIntegrationTest.java
Labels: bug

#535 [HTM-885] Handle additionalProperties.connectOptions when connecting to a database
  src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/nl/b3p/tailormap/api/geotools/featuresources/JDBCFeatureSourceHelper.java
  src/main/resources/openapi/persistence-schemas.yaml
Labels: enhancement

#539 Dependency updates
  pom.xml
Labels: dependency, security
