Repository Tailormap/tailormap-api, pull requests merged in 2023-06, with the labels that each got.

#476 [HTM-800] Add attribution to AppLayer
  src/main/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelper.java
  src/main/java/nl/b3p/tailormap/api/persistence/helper/GeoServiceHelper.java
  src/main/resources/openapi/persistence-schemas.yaml
  src/main/resources/openapi/viewer-schemas.yaml
Labels: enhancement

#477 [HTM-521] Add some test attribution data
  src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java
Labels: enhancement

#478 [HTM-776] Remove any members from a group before removing the group
  src/main/java/nl/b3p/tailormap/api/persistence/Group.java
Labels: bug

#486 [HTM-797] Remove unwanted parameters from a geoservice url before storing
  src/main/java/nl/b3p/tailormap/api/persistence/GeoService.java
  src/test/java/nl/b3p/tailormap/api/persistence/GeoServiceTest.java
Labels: bug, enhancement

#485 [HTM-806] Handle app layer description in the API
  src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/nl/b3p/tailormap/api/persistence/GeoService.java
  src/main/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelper.java
  src/main/java/nl/b3p/tailormap/api/util/TMStringUtils.java
  src/main/resources/openapi/persistence-schemas.yaml
  src/main/resources/openapi/viewer-schemas.yaml
Labels: enhancement

#490 Update ubuntu-maven.yml
  .github/workflows/ubuntu-maven.yml
Labels: infrastucture

#504 [HTM-835] Edit feature API endpoint implementation
  pom.xml
  src/main/java/nl/b3p/tailormap/api/controller/EditFeatureController.java
  src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
  src/main/java/nl/b3p/tailormap/api/geotools/processing/GeometryProcessor.java
  src/main/resources/application.properties
  src/main/resources/openapi/viewer-api.yaml
  src/test/java/nl/b3p/tailormap/api/controller/EditFeatureControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerPostgresIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerReConfiguredPostgresIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/geotools/processing/GeometryProcessorTest.java
  src/test/resources/StaticTestData.properties
  src/test/resources/junit-platform.properties
Labels: enhancement

#513 [HTM-840] Fix duplicated attributes after reloading feature source
  src/main/java/nl/b3p/tailormap/api/geotools/featuresources/FeatureSourceHelper.java
Labels: bug

#509 [HTM-843][HTM-859] Refactor Attribute model
  src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
  src/main/java/nl/b3p/tailormap/api/controller/LayerDescriptionController.java
  src/main/java/nl/b3p/tailormap/api/geotools/featuresources/FeatureSourceHelper.java
  src/main/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelper.java
  src/main/resources/openapi/persistence-schemas.yaml
  src/main/resources/openapi/viewer-schemas.yaml
  src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerPostgresIntegrationTest.java
Labels: enhancement
