Repository Tailormap/tailormap-api, pull requests merged in 2023-01, with the labels that each got.

#296 Bump dependency-check-maven.version to 7.4.4
  pom.xml
Labels: infrastucture

#294 [HTM-637] Return sorted unique values
  src/main/java/nl/b3p/tailormap/api/controller/UniqueValuesController.java
  src/main/resources/tailormap-api.yaml
  src/test/java/nl/b3p/tailormap/api/controller/UniqueValuesControllerPostgresIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/model/UniqueValuesResponseTest.java
Labels: bug

#302 Bump mssql-jdbc.version 11.2.2.jre11 ➜ 11.2.3.jre11
  pom.xml
Labels: dependency

#308 Revert "Bump dependency-check-maven from 7.4.4 to 8.0.0"
  pom.xml
Labels: infrastucture

#300 Layer export API
  pom.xml
  src/main/java/nl/b3p/tailormap/api/MicrometerHelper.java
  src/main/java/nl/b3p/tailormap/api/controller/GeoServiceProxyController.java
  src/main/java/nl/b3p/tailormap/api/controller/LayerExportController.java
  src/main/java/nl/b3p/tailormap/api/geotools/wfs/SimpleWFSHelper.java
  src/main/java/nl/b3p/tailormap/api/geotools/wfs/SimpleWFSLayerDescription.java
  src/main/java/nl/b3p/tailormap/api/geotools/wfs/WFSProxy.java
  src/main/java/nl/b3p/tailormap/api/util/HttpProxyUtil.java
  src/main/resources/model.yaml
  src/main/resources/tailormap-api.yaml
  src/test/java/nl/b3p/tailormap/api/controller/LayerExportControllerIntegrationTest.java
Labels: enhancement

#313 [HTM-623] Only return generic geometry type
  src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
Labels: bug

#312 [HTM-641] ConfiguredAttribute.getFeatureType() may be null when layer…
  src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
Labels: bug

#314 HTM-671: Ignore attributes with empty type, also HTM-623 for layer description controller
  pom.xml
  src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java
  src/main/java/nl/b3p/tailormap/api/controller/LayerDescriptionController.java
  src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerPostgresIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerPostgresIntegrationTest.java
Labels: bug
