Repository Tailormap/tailormap-api, pull requests merged in 2024-04, with the labels that each got.

#777 HTM-1032: Set SameSite=None for XSRF cookie to allow POST requests when embedded from different domain
  src/main/java/nl/b3p/tailormap/api/security/ApiSecurityConfiguration.java
Labels: enhancement, security

#781 HTM-1032: Disable CSRF filter for FeaturesController
  src/main/java/nl/b3p/tailormap/api/security/ApiSecurityConfiguration.java
Labels: enhancement

#783 Add additional properties to Group
  src/main/java/nl/b3p/tailormap/api/persistence/Group.java
  src/main/resources/db/migration/V6__group_additional_properties.sql
Labels: enhancement

#786 Dependency updates
  pom.xml
Labels: dependency

#797 [HTM-1103] Upgrade maven-pmd-plugin to 3.22.0 which defaults to PMD 7
  build/qa/pmd-junit-ruleset.xml
  build/qa/pmd-ruleset.xml
  pom.xml
Labels: infrastucture
