Repository Tailormap/tailormap-api, pull requests merged in 2024-10, with the labels that each got.

#973 HTM-1243: Suppress some irrelevant CVEs in OWASP scanner
  build/qa/owasp-suppression.xml
Labels: infrastructure

#975 HTM-1195: increase default maximum number of features
  src/main/java/org/tailormap/api/controller/FeaturesController.java
  src/main/java/org/tailormap/api/util/Constants.java
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: enhancement

#971 HTM-1223 | HTM-1228 | HTM-1229: Introduce and create Quartz scheduling functionality
  build/ci/docker-compose.yml
  build/ci/testdata-setup.sh
  build/qa/owasp-suppression.xml
  pom.xml
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java
  src/main/java/org/tailormap/api/scheduling/JobCreator.java
  src/main/java/org/tailormap/api/scheduling/PocTask.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V10__quartz_persistence.sql
  src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java
  src/test/resources/application-postgresql.properties
  src/test/resources/application.properties
Labels: enhancement

#976 HTM-1161: Add authentication event logging
  src/main/java/org/tailormap/api/security/ApiSecurityConfiguration.java
  src/main/java/org/tailormap/api/security/AuthenticationEvents.java
  src/main/java/org/tailormap/api/security/events/DefaultAuthenticationFailureEvent.java
  src/main/java/org/tailormap/api/security/events/OAuth2AuthenticationFailureEvent.java
  src/main/resources/application.properties
Labels: enhancement

#979 HTM-1221: common interface for creating tasks
  src/main/java/org/tailormap/api/configuration/SchedulerConfiguration.java
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java
  src/main/java/org/tailormap/api/scheduling/DebugLoggingJobListener.java
  src/main/java/org/tailormap/api/scheduling/DebugLoggingTriggerListener.java
  src/main/java/org/tailormap/api/scheduling/PocTask.java
  src/main/java/org/tailormap/api/scheduling/TMJobDataMap.java
  src/main/java/org/tailormap/api/scheduling/TaskCreator.java
  src/main/java/org/tailormap/api/util/Constants.java
  src/main/resources/application.properties
  src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java
  src/test/java/org/tailormap/api/scheduling/TMJobDataMapTest.java
Labels: enhancement

#984 HTM-1225: implement prioritising job triggers
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/scheduling/TMJobDataMap.java
  src/main/java/org/tailormap/api/scheduling/TaskCreator.java
  src/test/java/org/tailormap/api/scheduling/TMJobDataMapTest.java
Labels: enhancement

#988 HTM-1227: expose the quartz actuator endpoint
  src/main/resources/application.properties
Labels: enhancement

#983 HTM-952: Fix regression allowing access to proxied-with-auth layers in public apps (with or without login)
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/controller/AppRestControllerAdvice.java
  src/main/java/org/tailormap/api/controller/GeoServiceProxyController.java
  src/main/java/org/tailormap/api/persistence/helper/ApplicationHelper.java
  src/main/java/org/tailormap/api/security/AuthorizationService.java
  src/test/java/org/tailormap/api/controller/FeaturesControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/GeoServiceProxyControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/LayerDescriptionControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/LayerExportControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/SearchControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/TestUrls.java
  src/test/java/org/tailormap/api/controller/UniqueValuesControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/ViewerControllerIntegrationTest.java
Labels: bug, security

#990 HTM-1227: allow monitoring of triggered jobs through Sentry
  pom.xml
  src/main/java/org/tailormap/api/configuration/SchedulerConfiguration.java
  src/main/java/org/tailormap/api/scheduling/TaskCreator.java
Labels: enhancement

#992 HTM-1259: Dependency updates: flyway, micrometer
  pom.xml
Labels: dependency

#994 HTM-1252: Upgrade Spring Data to 2024.0.5
  pom.xml
Labels: dependency

#995 HTM-1274: Bump jetty.version to 10.0.24
  pom.xml
Labels: dependency, security

#991 HTM-1254|HTM-1255|HTM-1256|HTM-1257: Make creating full-text indexes on schedule as part of task framework possible
  src/main/java/org/tailormap/api/configuration/base/WebMvcConfig.java
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java
  src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java
  src/main/java/org/tailormap/api/persistence/SearchIndex.java
  src/main/java/org/tailormap/api/repository/SearchIndexRepository.java
  src/main/java/org/tailormap/api/repository/events/SearchIndexEventHandler.java
  src/main/java/org/tailormap/api/scheduling/FailingPocTask.java
  src/main/java/org/tailormap/api/scheduling/IndexTask.java
  src/main/java/org/tailormap/api/scheduling/PocTask.java
  src/main/java/org/tailormap/api/scheduling/TMJobDataMap.java
  src/main/java/org/tailormap/api/scheduling/Task.java
  src/main/java/org/tailormap/api/scheduling/TaskCreator.java
  src/main/java/org/tailormap/api/scheduling/TaskManagerService.java
  src/main/java/org/tailormap/api/scheduling/TaskType.java
  src/main/java/org/tailormap/api/solr/SolrHelper.java
  src/main/resources/db/migration/V11__add_solr_index_schedule_column.sql
  src/main/resources/openapi/admin-schemas.yaml
  src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java
  src/test/java/org/tailormap/api/scheduling/TMJobDataMapTest.java
Labels: enhancement

#996 HTM-1253: fix java.lang.IllegalStateException: JobStore is shutdown - aborting retry
  src/main/resources/application.properties
Labels: bug

#1000 HTM-1278: Update org.junit:junit-bom from v5.11.2 to v5.11.3
  pom.xml
Labels: dependency

#999 ⛓️‍💥 HTM-1266: explicitly create the INDEX_DISPLAY_FIELD and INDEX_SEARCH_FIELD to make sure these are of the required type ⛓️‍💥
  src/main/java/org/tailormap/api/solr/SolrHelper.java
Labels: bug, breaking

#1006 HTM-1258: Allow storing only one task per search index
  src/main/java/org/tailormap/api/repository/events/SearchIndexEventHandler.java
  src/test/java/org/tailormap/api/repository/events/SearchIndexEventHandlerIntegrationTest.java
Labels: bug

#998 HTM-1251: Upgrade Spring Boot from 3.3.4 to 3.3.5, rely on the `spring-security.version` provided by Spring Boot
  pom.xml
Labels: dependency, security

#1008 HTM-1288: Upgrade PMD to latest release
  build/qa/PMD-ruleset_for_TM.xml
  build/qa/pmd-junit-ruleset.xml
  pom.xml
  src/test/java/org/tailormap/api/controller/AppControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/ConfigurationControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/EditFeatureControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/FeaturesControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/GeoServiceProxyControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/LayerDescriptionControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/LayerExportControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/SearchControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/UniqueValuesControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/UniqueValuesControllerReConfiguredIntegrationTest.java
  src/test/java/org/tailormap/api/controller/UploadsControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/UserControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/ViewerControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/admin/ApplicationAdminControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/admin/FeatureSourceAdminControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/admin/GeoServiceAdminControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/admin/JSR303ValidationIntegrationTest.java
  src/test/java/org/tailormap/api/controller/admin/PasswordValidationControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/admin/PersistentJsonArrayPropertyIntegrationTest.java
  src/test/java/org/tailormap/api/controller/admin/SolrAdminControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/admin/UnreachableSolrAdminControllerIntegrationTest.java
  src/test/java/org/tailormap/api/repository/events/SearchIndexEventHandlerIntegrationTest.java
  src/test/java/org/tailormap/api/repository/validation/SearchIndexValidatorIntegrationTest.java
  src/test/java/org/tailormap/api/security/ActuatorSecurityConfigurationIntegrationTest.java
  src/test/java/org/tailormap/api/security/ApiSecurityConfigurationIntegrationTest.java
Labels: infrastructure
