Repository Tailormap/tailormap-api, pull requests merged in 2024-03, with the labels that each got.

#739 [HTM-1036] Java 17 compiler and runtime upgrade
  .github/workflows/macos-maven.yml
  .github/workflows/owasp-dependency-check.yml
  .github/workflows/qa.yml
  .github/workflows/trivy.yml
  .github/workflows/ubuntu-maven.yml
  .github/workflows/windows-maven.yml
  .mvn/jvm.config
  Dockerfile
  pom.xml
Labels: enhancement, infrastucture

#736 [HTM-1043] Add German locale
  src/main/java/nl/b3p/tailormap/api/configuration/base/FrontController.java
Labels: enhancement

#750 Dependency updates
  pom.xml
Labels: dependency

#754 [HTM-1050] review/fix/delete @Disabled tests
  src/test/java/nl/b3p/tailormap/api/controller/LayerDescriptionControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/ViewerControllerIntegrationTest.java
Labels: bug

#756 Bump dependency-check-maven.version from 9.0.9 to 9.0.10
  pom.xml
Labels: infrastucture

#758 [CI] all builds require Maven 3.9.5 or higher
  .github/workflows/codeql-analysis.yml
  .github/workflows/ubuntu-maven.yml
  .github/workflows/windows-maven.yml
Labels: infrastucture

#738 Bump GeoTools from 30.2 to 31.0
  pom.xml
Labels: dependency

#763 [HTM-1061] Fix anonymous user access and user login
  src/main/java/nl/b3p/tailormap/api/security/ActuatorSecurityConfiguration.java
  src/main/java/nl/b3p/tailormap/api/security/ApiSecurityConfiguration.java
  src/main/java/nl/b3p/tailormap/api/security/AuditInterceptor.java
  src/test/java/nl/b3p/tailormap/api/annotation/PostgresIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/EditFeatureControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/GeoServiceProxyControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/admin/ApplicationAdminControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/controller/admin/PasswordValidationControllerIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/security/ActuatorSecurityConfigurationIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/security/ApiSecurityConfigurationIntegrationTest.java
  src/test/java/nl/b3p/tailormap/api/security/TestSecurityConfig.java
  src/test/resources/application.properties
Labels: bug

#765 [HTM-1069] Update dependabot config
  .github/dependabot.yml
Labels: infrastucture

#770 HTM-1070: Fix Spring Boot CSRF problems for SPA
  src/main/java/nl/b3p/tailormap/api/security/ApiSecurityConfiguration.java
  src/main/java/nl/b3p/tailormap/api/security/CsrfCookieFilter.java
Labels: bug
