Repository Tailormap/tailormap-api, pull requests merged in 2024-09, with the labels that each got.

#934 Bump org.apache.commons:commons-lang3 from 3.16.0 to 3.17.0
  pom.xml
Labels: dependency

#935 Disable LayerExportControllerIntegrationTest#shouldNotExportHiddenAttributesInGeoJSON
  src/test/java/org/tailormap/api/controller/LayerExportControllerIntegrationTest.java
Labels: tests

#936 HTM-1029: Update Maven runtime in workflows
  .github/workflows/macos-maven.yml
  .github/workflows/owasp-dependency-check.yml
  .github/workflows/qa.yml
  .github/workflows/trivy.yml
  .github/workflows/ubuntu-maven.yml
  .github/workflows/windows-maven.yml
Labels: infrastructure

#937 Generate sources before running CodeQL
  .github/workflows/codeql.yml
Labels: infrastructure

#938 HTM-1162: Configure logfile so it can be retrieved using actuator
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: enhancement

#939 Revert "Bump org.apache.maven.plugins:maven-scm-publish-plugin from 3.2.1 to 3.3.0"
  pom.xml
Labels: bug, infrastructure

#943 HTM-1206: disable Solr indexing for WFS feature types
  src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java
  src/main/java/org/tailormap/api/repository/validation/SearchIndexValidator.java
  src/main/java/org/tailormap/api/repository/validation/ValidationConfiguration.java
  src/test/java/org/tailormap/api/repository/validation/SearchIndexValidatorIntegrationTest.java
Labels: bug

#944 HTM-1208: Add caching for Trivy
  .github/workflows/trivy.yml
Labels: infrastructure

#946 HTM-1211: Some code improvements for Solr functionality
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/controller/SearchController.java
  src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java
  src/main/java/org/tailormap/api/repository/FeatureSourceRepository.java
  src/main/java/org/tailormap/api/repository/FeatureTypeRepository.java
  src/main/java/org/tailormap/api/solr/SolrHelper.java
  src/main/java/org/tailormap/api/solr/SolrService.java
  src/test/java/org/tailormap/api/repository/validation/SearchIndexValidatorIntegrationTest.java
Labels: bug

#948 HTM-1212: fix deprecations in site descriptor, update logo
  .mvn/extensions.xml
  pom.xml
  src/site/resources/images/logo.png
  src/site/site.xml
Labels: bug, documentation, infrastructure

#950 HTM-1214: dependency updates
  pom.xml
Labels: dependency

#951 HTM-1215: update Codecov config to upload tests
  .github/workflows/macos-maven.yml
  .github/workflows/ubuntu-maven.yml
  .github/workflows/windows-maven.yml
Labels: infrastructure

#923 HTM-1039: Upgrade to GeoTools 32.0 / JTS 1.20.0
  pom.xml
Labels: dependency

#953 HTM-1220: initial (scheduled/background) task controller to determine the API
  src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java
  src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java
Labels: enhancement
