Repository Tailormap/tailormap-api, pull requests merged in 2024-06, with the labels that each got.

#839 HTM-998: Add uploads for logo and legends
  src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/nl/b3p/tailormap/api/controller/UploadsController.java
  src/main/java/nl/b3p/tailormap/api/controller/ViewerController.java
  src/main/java/nl/b3p/tailormap/api/persistence/Upload.java
  src/main/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelper.java
  src/main/java/nl/b3p/tailormap/api/persistence/projections/UploadSummary.java
  src/main/java/nl/b3p/tailormap/api/repository/UploadRepository.java
  src/main/java/nl/b3p/tailormap/api/util/Constants.java
  src/main/resources/db/migration/V9__upload.sql
  src/main/resources/openapi/persistence-schemas.yaml
  src/main/resources/test/gemeentegebied-legend.png
  src/main/resources/test/gradient-logo.svg
  src/test/java/nl/b3p/tailormap/api/controller/AppControllerIntegrationTest.java
Labels: enhancement

#847 [ci] Update Maven version to 3.9.7
  .github/workflows/codeql-analysis.yml
  .github/workflows/macos-maven.yml
  .github/workflows/owasp-dependency-check.yml
  .github/workflows/qa.yml
  .github/workflows/trivy.yml
  .github/workflows/ubuntu-maven.yml
  .github/workflows/windows-maven.yml
Labels: infrastucture

#848 [HTM-1123] Fix expected location of SBOM file
  .github/workflows/ubuntu-maven.yml
Labels: infrastucture

#846 [HTM-1127] Change XEPDB1 to FREEPDB1 so we can benefit from the Oracle upgrade to 23.4
  build/ci/docker-compose.yml
  src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java
Labels: infrastucture

#854 HTM-1120: Use legend URL from first Style from capabilities
  src/main/java/nl/b3p/tailormap/api/persistence/helper/ApplicationHelper.java
Labels: enhancement

#855 Dependency updates
  pom.xml
Labels: dependency

#856 HTM-1129: fix metrics application label
  src/main/resources/application.properties
Labels: bug
