Repository Tailormap/tailormap-api, pull requests merged in 2024-02, with the labels that each got.

#709 Update Codecov action to v4
  .github/workflows/macos-maven.yml
  .github/workflows/ubuntu-maven.yml
  .github/workflows/windows-maven.yml
Labels: infrastucture

#707 Dependency updates
  .github/workflows/macos-maven.yml
  .github/workflows/ubuntu-maven.yml
  .github/workflows/windows-maven.yml
  pom.xml
Labels: dependency, security

#712 HTM-1007: Set Cache-Control for index.html and version.json
  src/main/java/nl/b3p/tailormap/api/configuration/base/WebMvcConfig.java
Labels: enhancement

#713 HTM-1000: Enable compression
  src/main/java/nl/b3p/tailormap/api/configuration/base/WebMvcConfig.java
  src/main/resources/application.properties
Labels: enhancement

#716 HTM-990: Only set WFS title if not already set by user
  src/main/java/nl/b3p/tailormap/api/geotools/featuresources/FeatureSourceHelper.java
Labels: bug

#718 HTM-1009: CRS for XYZ layer
  src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/nl/b3p/tailormap/api/persistence/helper/GeoServiceHelper.java
  src/main/java/nl/b3p/tailormap/api/repository/validation/GeoServiceValidator.java
  src/main/resources/openapi/persistence-schemas.yaml
Labels: enhancement

#720 [HTM-1003] Add `ApplicationName=tailormap-api` to any PostgreSQL connection
  src/main/java/nl/b3p/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/nl/b3p/tailormap/api/geotools/featuresources/JDBCFeatureSourceHelper.java
Labels: enhancement

#721 fix testcases for odd pdok wfs
  src/test/java/nl/b3p/tailormap/api/controller/FeaturesControllerIntegrationTest.java
Labels: bug, infrastucture

#728 [infra] Move postgres service to compose file
  .github/workflows/ubuntu-maven.yml
  .mvn/maven.config
  build/ci/docker-compose.yml
Labels: infrastucture

#731 Update pgjdbc to 42.7.2 to workaround CVE-2024-1597, also update mssql jdbc driver to latest patch version
  pom.xml
Labels: dependency, security

#732 Bump spring-security.version from 5.8.9 to 5.8.10
  pom.xml
Labels: dependency
