Repository Tailormap/tailormap-api, pull requests merged in 2024-11, with the labels that each got.

#1021 HTM-1315 | HTM-1316: Implement startTask() and stopTask() methods
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java
  src/main/java/org/tailormap/api/scheduling/InterruptablePocTask.java
  src/main/java/org/tailormap/api/scheduling/Task.java
  src/main/java/org/tailormap/api/scheduling/TaskType.java
  src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java
Labels: enhancement

#1024 HTM-1313: prevent submitting bogus document to Solr
  src/main/java/org/tailormap/api/solr/SolrHelper.java
Labels: bug

#1025 ⛓️‍💥 HTM-1091: Add feature geometry as a strong-type ⛓️‍💥
  build/ci/docker-compose.yml
  src/main/java/org/tailormap/api/controller/SearchController.java
  src/main/java/org/tailormap/api/solr/SolrHelper.java
  src/main/resources/openapi/viewer-api.yaml
  src/test/java/org/tailormap/api/controller/SearchControllerIntegrationTest.java
Labels: enhancement, breaking

#1029 HTM-1321: Make Solr schema creation more robust
  src/main/java/org/tailormap/api/solr/SolrHelper.java
  src/test/java/org/tailormap/api/controller/admin/UnreachableSolrAdminControllerIntegrationTest.java
Labels: bug

#1030 HTM-1091: Enable bbox filtering for Solr search
  src/main/java/org/tailormap/api/solr/SolrHelper.java
  src/test/java/org/tailormap/api/controller/SearchControllerIntegrationTest.java
Labels: enhancement

#1031 HTM-1286: Fix code scanning alert no. 352: Server-side request forgery
  src/main/java/org/tailormap/api/controller/LayerExportController.java
  src/main/resources/application.properties
  src/test/java/org/tailormap/api/controller/LayerExportControllerIntegrationTest.java
  src/test/resources/application.properties
Labels: bug

#1034 Bump quartz.version from 2.3.2 to 2.4.0
  pom.xml
Labels: dependency

#1035 Bump quartz.version from 2.4.0 to 2.5.0
  pom.xml
Labels: dependency

#1048 Allow schedule to have `null` priority when updating a search index
  src/main/java/org/tailormap/api/repository/events/SearchIndexEventHandler.java
  src/main/java/org/tailormap/api/scheduling/TMJobDataMap.java
  src/main/java/org/tailormap/api/scheduling/TaskManagerService.java
Labels: bug

#1050 HTM-1242: remove arm64 building from API
  .github/workflows/ubuntu-maven.yml
  pom.xml
Labels: infrastructure

#1051 HTM-1333: Fix error saving a user who has group memberships
  pom.xml
Labels: bug

#1054 Some small CI updates and clean away tailormap.log s
  .github/workflows/macos-maven.yml
  .github/workflows/ubuntu-maven.yml
  .github/workflows/windows-maven.yml
  pom.xml
Labels: infrastructure

#1037 HTM-1330: Upgrade Spring Boot 3.3.5 ⇥ 3.3.6
  pom.xml
Labels: dependency

#1043 HTM-1331: Make sure we cleanup the schedule when a task is deleted
  src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java
  src/main/java/org/tailormap/api/repository/SearchIndexRepository.java
  src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java
Labels: bug

#1052 ⛓️‍💥 HTM-1332: fix Solr indexing timeouts ⛓️‍💥
  build/ci/docker-compose.yml
  pom.xml
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/controller/SearchController.java
  src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java
  src/main/java/org/tailormap/api/scheduling/IndexTask.java
  src/main/java/org/tailormap/api/solr/SolrHelper.java
  src/main/java/org/tailormap/api/solr/SolrService.java
  src/main/resources/application.properties
Labels: bug, breaking

#1057 Allow priority to be null when creating a new task
  src/main/java/org/tailormap/api/repository/events/SearchIndexEventHandler.java
Labels: bug

#1060 Fix error persisting detached entity
  src/test/java/org/tailormap/api/controller/AppControllerIntegrationTest.java
Labels: bug

#1059 HTM-1348: Update JobDetail when updating a task
  src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java
  src/main/java/org/tailormap/api/scheduling/TaskManagerService.java
Labels: bug

#1058 HTM-1336: Added Page persistence + admin and viewer api endpoints
  src/main/java/org/tailormap/api/controller/PageController.java
  src/main/java/org/tailormap/api/persistence/Configuration.java
  src/main/java/org/tailormap/api/persistence/Page.java
  src/main/java/org/tailormap/api/repository/PageRepository.java
  src/main/resources/db/migration/V12__page.sql
  src/main/resources/openapi/persistence-schemas.yaml
  src/main/resources/openapi/viewer-api.yaml
  src/main/resources/openapi/viewer-schemas.yaml
Labels: enhancement

#1061 HTM-1349: Consolidate logging libraries and ban old junit
  pom.xml
Labels: infrastructure
