Repository Tailormap/tailormap-api, pull requests merged in 2024-12, with the labels that each got.

#1064 HTM-1073: Start a manual indexing job on the scheduler instead of in the request thread
  pom.xml
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java
  src/main/java/org/tailormap/api/scheduling/TaskManagerService.java
  src/test/java/org/tailormap/api/controller/admin/SolrAdminControllerIntegrationTest.java
  src/test/resources/application.properties
Labels: enhancement

#1068 HTM-1351: Add EntityListeners annotation to enable sending SSE when updates occur
  src/main/java/org/tailormap/api/persistence/SearchIndex.java
Labels: bug

#1071 Add option to skip testdata categories
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/resources/application-populate-testdata.properties
Labels: tests

#1069 Add page tile image url + some refactoring
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/controller/PageController.java
  src/main/java/org/tailormap/api/controller/ViewerController.java
  src/main/java/org/tailormap/api/persistence/Page.java
  src/main/java/org/tailormap/api/persistence/Upload.java
  src/main/java/org/tailormap/api/persistence/helper/UploadHelper.java
  src/main/resources/application-populate-testdata.properties
  src/test/java/org/tailormap/api/controller/PageControllerIntegrationTest.java
Labels: enhancement

#1072 HTM-1356: Dev/add menu to page response
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/controller/PageController.java
  src/main/java/org/tailormap/api/persistence/Configuration.java
  src/main/resources/openapi/persistence-schemas.yaml
  src/main/resources/openapi/viewer-schemas.yaml
  src/test/java/org/tailormap/api/controller/PageControllerIntegrationTest.java
Labels: enhancement

#1076 HTM-1358: Remove unused commons-codec
  pom.xml
Labels: dependency

#1077 Add a devcontainer config
  build/ci/docker-compose.yml
Labels: infrastructure

#1080 Add forgotten files of #1077
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
Labels: infrastructure

#1079 HTM-1362: fix Inconsistency in naming of the returned task
  src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java
  src/test/java/org/tailormap/api/controller/admin/SolrAdminControllerIntegrationTest.java
Labels: bug

#1078 HTM-1359 | HTM-1360: Scheduled tasks should emit events on progress
  src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java
  src/main/java/org/tailormap/api/scheduling/IndexTask.java
  src/main/java/org/tailormap/api/scheduling/PocTask.java
  src/main/java/org/tailormap/api/scheduling/Task.java
  src/main/java/org/tailormap/api/solr/SolrHelper.java
  src/main/resources/openapi/admin-schemas.yaml
Labels: enhancement

#1086 HTM-1372: add operationIds for the page endpoints
  src/main/resources/openapi/viewer-api.yaml
Labels: bug

#1087 HTM-1375: fix OpenAPI errors and warnings
  src/main/resources/openapi/viewer-api.yaml
  src/main/resources/openapi/viewer-schemas.yaml
Labels: bug

#1082 HTM-1366 | HTM-1367: Indexing process summary information should be stored as a json blob
  src/main/java/org/tailormap/api/controller/admin/SolrAdminController.java
  src/main/java/org/tailormap/api/persistence/SearchIndex.java
  src/main/java/org/tailormap/api/scheduling/IndexTask.java
  src/main/java/org/tailormap/api/solr/SolrHelper.java
  src/main/resources/db/migration/V13__add_solr_index_summary_delete_comment_columns.sql
  src/main/resources/openapi/admin-schemas.yaml
Labels: enhancement

#1085 Fix: use doesNotHaveJsonPath() when expecting that a path should not exist
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/test/java/org/tailormap/api/controller/FeaturesControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/LayerDescriptionControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/LayerExportControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/PageControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/TestUrls.java
  src/test/java/org/tailormap/api/controller/ViewerControllerIntegrationTest.java
Labels: bug, tests

#1091 HTM-1379: remove dependency track buildsteps in tailormap-api
  .github/workflows/ubuntu-maven.yml
  pom.xml
Labels: infrastructure

#1096 HTM-1393 | HTM-1394: Override logback version provided by Spring Boot bom from 1.5.12 to 1.5.14
  pom.xml
Labels: dependency, security

#1094 HTM-1389: add test data for search filtering
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/test/java/org/tailormap/api/controller/AppControllerIntegrationTest.java
Labels: enhancement

#1097 Rewrite the front controller to use a ResourceResolver so not all possible routes need to be mapped
  src/main/java/org/tailormap/api/configuration/base/FrontController.java
  src/main/java/org/tailormap/api/configuration/base/FrontControllerResolver.java
  src/main/java/org/tailormap/api/configuration/base/IndexHtmlTransformer.java
  src/main/java/org/tailormap/api/configuration/base/WebMvcConfig.java
  src/main/resources/application-static-only.properties
  src/main/resources/application.properties
Labels: enhancement
