Repository Tailormap/tailormap-api, pull requests merged in 2025-08, with the labels that each got.

#1332 HTM-1605: Add code to generate application request metric in ViewerController
  src/main/java/org/tailormap/api/controller/IngestMetricsController.java
  src/main/java/org/tailormap/api/controller/ViewerController.java
  src/main/java/org/tailormap/api/prometheus/TagNames.java
  src/test/java/org/tailormap/api/controller/ViewerControllerWithActuatorIntegrationTest.java
Labels: enhancement

#1339 Assorted dependency updates
  pom.xml
Labels: dependency, security

#1333 HTM-1606: Update CI stack to include a configured prometheus service
  build/ci/compose-config-files/prometheus.yaml
  build/ci/docker-compose.yml
  pom.xml
  src/main/java/org/tailormap/api/prometheus/PrometheusResultProcessor.java
  src/main/resources/application.properties
  src/test/java/org/tailormap/api/PrometheusIntegrationTest.java
  src/test/java/org/tailormap/api/controller/IngestMetricsControllerIntegrationTest.java
  src/test/java/org/tailormap/api/prometheus/PrometheusResultProcessorTest.java
Labels: enhancement

#1350 Bump Solr jetty.version override from 10.0.24 to 10.0.26
  pom.xml
Labels: dependency

#1353 Allow actuator access from internal networks and localhost
  build/ci/compose-config-files/prometheus.yaml
  src/main/java/org/tailormap/api/security/ActuatorSecurityConfiguration.java
  src/test/java/org/tailormap/api/security/ActuatorSecurityConfigurationIntegrationTest.java
Labels: infrastructure
