Repository Tailormap/tailormap-api, pull requests merged in 2025-07, with the labels that each got.

#1284 Add admin controller to find uploads by md5 of content
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/controller/admin/FindUploadsByHashController.java
  src/main/java/org/tailormap/api/repository/UploadMatch.java
  src/main/java/org/tailormap/api/repository/UploadRepository.java
  src/main/resources/test/object-drawing-style.json
  src/test/java/org/tailormap/api/controller/UploadsControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/admin/FindUploadsByHashControllerIntegrationTest.java
Labels: enhancement

#1289 Bump hibernate.version from 6.6.18.Final to 6.6.19.Final
  pom.xml
Labels: dependency

#1307 HTM-1593: fix faulty testcase
  src/test/java/org/tailormap/api/controller/admin/UniqueValuesAdminControllerIntegrationTest.java
Labels: bug

#1311 Update Maven version from 3.9.9 to 3.9.11
  .github/workflows/codeql.yml
  .github/workflows/macos-maven.yml
  .github/workflows/owasp-dependency-check.yml
  .github/workflows/qa.yml
  .github/workflows/trivy.yml
  .github/workflows/ubuntu-maven.yml
Labels: infrastructure

#1312 HTM-1586: Allow proxying layers from secured services for authenticated users
  src/main/java/org/tailormap/api/controller/AppRestControllerAdvice.java
  src/main/java/org/tailormap/api/controller/GeoServiceProxyController.java
  src/main/java/org/tailormap/api/persistence/helper/ApplicationHelper.java
  src/main/java/org/tailormap/api/security/AuthorisationService.java
  src/test/java/org/tailormap/api/controller/ViewerControllerIntegrationTest.java
Labels: enhancement
