Repository Tailormap/tailormap-api, pull requests merged in 2025-01, with the labels that each got.

#1102 HTM-1398: refactor task keys
  src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java
  src/main/java/org/tailormap/api/scheduling/IndexTask.java
  src/main/java/org/tailormap/api/scheduling/InterruptablePocTask.java
  src/main/java/org/tailormap/api/scheduling/PocTask.java
  src/main/java/org/tailormap/api/scheduling/Task.java
Labels: enhancement

#1104 HTM-1399|HTM-1400: Dependency updates
  pom.xml
Labels: dependency

#1105 HTM-1401 | HTM-1402 | HTM-1403: Update task-progress event to have optional map of task data and use it to transmit eg. indexId
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/scheduling/InterruptablePocTask.java
  src/main/java/org/tailormap/api/scheduling/PocTask.java
  src/main/java/org/tailormap/api/solr/SolrHelper.java
  src/main/resources/openapi/admin-schemas.yaml
Labels: enhancement

#1106 HTM-1405: Add kadastrale aanduiding layer and search index in default app
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/test/java/org/tailormap/api/controller/SearchControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/ViewerControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/admin/FeatureSourceAdminControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java
  src/test/resources/application.properties
Labels: tests

#1110 HTM-1298: Add aliasForGroup to grant an additional authority when user is member of a (SSO-)group
  src/main/java/org/tailormap/api/persistence/Group.java
  src/main/java/org/tailormap/api/security/ApiSecurityConfiguration.java
  src/main/java/org/tailormap/api/security/TailormapUserDetails.java
  src/main/resources/db/migration/V14__group_alias_for.sql
Labels: enhancement

#1112 HTM-1410/HTM-1411: Add OIDC information
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/persistence/Group.java
  src/main/java/org/tailormap/api/persistence/User.java
  src/main/java/org/tailormap/api/persistence/helper/AdminAdditionalPropertyHelper.java
  src/main/java/org/tailormap/api/security/ApiSecurityConfiguration.java
  src/main/java/org/tailormap/api/security/AuthenticationEventsLogger.java
  src/main/java/org/tailormap/api/security/OIDCAuthenticationEventsHandler.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V15__built_in_group_defaults.sql
Labels: enhancement

#1116 HTM-1413: when there are no attributes left indexing could crash
  src/main/java/org/tailormap/api/solr/SolrHelper.java
Labels: bug

#1123 Fix PDOK WFS integration tests, Utrecht got a new fid
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/test/java/org/tailormap/api/controller/FeaturesControllerIntegrationTest.java
  src/test/resources/StaticTestData.properties
Labels: tests

#1129 HTM-1421: Upgrade Solr from 9.7.0 to 9.8.0
  build/ci/docker-compose.yml
Labels: infrastructure, tests

#1130 Bump geotools.version from 32.1 to 32.2
  pom.xml
  src/main/java/org/tailormap/api/geotools/featuresources/JDBCFeatureSourceHelper.java
Labels: enhancement, dependency

#1133 SUPPORT-14840: re-enable and fix the `shouldNotExportHiddenAttributesInGeoJSON` testcase
  src/test/java/org/tailormap/api/controller/LayerExportControllerIntegrationTest.java
Labels: tests

#1136 HTM-1428: prevent NPE when a feature type has no primary key or geometry and admin erroneously wants to create a Solr index from it
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/solr/SolrHelper.java
  src/test/java/org/tailormap/api/solr/SolrHelperIntegrationTest.java
Labels: bug

#1127 HTM-1307: Add quantized mesh protocol layers and terrain layer tree
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/persistence/helper/ApplicationHelper.java
  src/main/java/org/tailormap/api/persistence/helper/GeoServiceHelper.java
  src/main/resources/openapi/common-schemas.yaml
  src/main/resources/openapi/persistence-schemas.yaml
  src/main/resources/openapi/viewer-api.yaml
  src/test/java/org/tailormap/api/controller/AppControllerIntegrationTest.java
  src/test/java/org/tailormap/api/controller/ViewerControllerIntegrationTest.java
Labels: enhancement
