Repository Tailormap/tailormap-api, pull requests merged in 2025-02, with the labels that each got.

#1140 HTM-1431: Add defaultGeometryColumn and primaryKeyAttribute in feature type summary
  src/main/java/org/tailormap/api/persistence/projections/TMFeatureSourceSummary.java
Labels: enhancement

#1144 Support frontends built without localization
  src/main/java/org/tailormap/api/configuration/base/FrontControllerResolver.java
Labels: enhancement

#1147 Autodetect which language bundles are available
  src/main/java/org/tailormap/api/configuration/base/FrontControllerResolver.java
  src/main/resources/application-static-only.properties
  src/main/resources/application.properties
Labels: infrastructure

#1149 [HTM-1436] Override json-smart.version to obtain a version that has fixed CVE-2024-57699
  pom.xml
Labels: dependency

#1150 Fix `Unauthorized` reponse for getHomePage and getPage
  src/main/resources/openapi/viewer-api.yaml
Labels: bug

#1159 HTM-1439: Add webMercatorAvailable flag to layers in the map response in the back-end
  src/main/java/org/tailormap/api/persistence/GeoService.java
  src/main/java/org/tailormap/api/persistence/helper/ApplicationHelper.java
  src/main/resources/openapi/viewer-schemas.yaml
Labels: enhancement

#1160 HTM-1441: set writeable property when JDBC feature type is not read only and no composite keys are found
  build/ci/testdata-setup.sh
  src/main/java/org/tailormap/api/geotools/featuresources/FeatureSourceHelper.java
  src/test/java/org/tailormap/api/controller/EditFeatureControllerIntegrationTest.java
Labels: bug
