Repository Tailormap/tailormap-api, pull requests merged in 2025-03, with the labels that each got.

#1151 ⛓️‍💥 EK-3 | EK-5 | EK-16: API for creating and manipulating drawings ⛓️‍💥
  .github/workflows/ubuntu-maven.yml
  build/ci/docker-compose.yml
  build/ci/testdata-setup.sh
  pom.xml
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/controller/DrawingController.java
  src/main/java/org/tailormap/api/drawing/DrawingService.java
  src/main/resources/application-dev.properties
  src/main/resources/application-populate-testdata.properties
  src/main/resources/application.properties
  src/main/resources/db/migration/V16__install_postgis.sql
  src/main/resources/db/migration/V17__create_data_schema.sql
  src/main/resources/openapi/viewer-api.yaml
  src/main/resources/openapi/viewer-schemas.yaml
  src/test/java/org/tailormap/api/controller/DrawingControllerIntegrationTest.java
  src/test/resources/application.properties
Labels: enhancement, breaking

#1166 Update openapi-generator-maven-plugin version to 7.12.0
  pom.xml
Labels: infrastructure

#1167 HTM-1451: temporarily disable failing PDOK service legend test
  src/test/java/org/tailormap/api/controller/GeoServiceProxyControllerIntegrationTest.java
Labels: bug

#1168 HTM-1452: sort drawings by creation date
  README.md
  build/ci/docker-compose.yml
  pom.xml
  src/main/java/org/tailormap/api/drawing/DrawingService.java
  src/test/java/org/tailormap/api/controller/DrawingControllerIntegrationTest.java
Labels: bug

#1174 Replace 'disabled' server type with 'generic'
  src/main/resources/openapi/persistence-schemas.yaml
Labels: bug

#1176 Add setting to hide functionality for a layer
  pom.xml
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/persistence/helper/ApplicationHelper.java
  src/main/resources/openapi/common-schemas-openapi-ignore
  src/main/resources/openapi/common-schemas.yaml
  src/main/resources/openapi/persistence-schemas.yaml
  src/main/resources/openapi/viewer-schemas.yaml
Labels: enhancement

#1182 HTM-1469: fix DrawingController does not return Feature id as part of GeoJSON
  src/main/java/org/tailormap/api/drawing/DrawingService.java
  src/test/java/org/tailormap/api/controller/DrawingControllerIntegrationTest.java
Labels: bug

#1190 HTM-1477: update Spring Boot parent (includes Spring Security) to resolve CVE-2025-22228
  pom.xml
Labels: bug, dependency, security
