Repository Tailormap/tailormap-api, pull requests merged in 2025-09, with the labels that each got.

#1354 HTM-1600: Cleanup the application and application layer metrics when an application is deleted
  src/main/java/org/tailormap/api/prometheus/PrometheusService.java
  src/main/java/org/tailormap/api/repository/events/ApplicationEventHandler.java
  src/test/java/org/tailormap/api/prometheus/PrometheusServiceIntegrationTest.java
  src/test/java/org/tailormap/api/repository/events/ApplicationEventHandlerIntegrationTest.java
Labels: enhancement

#1364 HTM-1273: cleanup PocTask, InterruptablePocTask and FailingPocTask
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/main/java/org/tailormap/api/controller/admin/TaskAdminController.java
  src/main/java/org/tailormap/api/scheduling/FailingPocTask.java
  src/main/java/org/tailormap/api/scheduling/InterruptablePocTask.java
  src/main/java/org/tailormap/api/scheduling/PocTask.java
  src/main/java/org/tailormap/api/scheduling/Task.java
  src/main/java/org/tailormap/api/scheduling/TaskType.java
  src/main/java/org/tailormap/api/util/Constants.java
  src/main/resources/application-populate-testdata.properties
  src/test/java/org/tailormap/api/controller/admin/TaskAdminControllerIntegrationTest.java
Labels: infrastructure

#1375 HTM-1645: Apply layer access rules to filters
  src/main/java/org/tailormap/api/controller/ViewerController.java
  src/main/java/org/tailormap/api/persistence/Application.java
  src/main/java/org/tailormap/api/persistence/helper/ViewerHelper.java
Labels: bug

#1377 HTM-1657: Fix login problems for user where additional_properties is null
  src/main/java/org/tailormap/api/security/TailormapUserDetails.java
Labels: bug

#1401 HTM-1680: Fix drawing admin / read-all authorizations
  src/main/java/org/tailormap/api/controller/UserController.java
  src/main/java/org/tailormap/api/drawing/DrawingService.java
  src/main/java/org/tailormap/api/repository/GroupRepository.java
  src/main/java/org/tailormap/api/security/ApiSecurityConfiguration.java
  src/main/java/org/tailormap/api/security/TailormapAdditionalProperty.java
  src/main/java/org/tailormap/api/security/TailormapOidcUser.java
  src/main/java/org/tailormap/api/security/TailormapOidcUserService.java
  src/main/java/org/tailormap/api/security/TailormapUserDetails.java
  src/main/java/org/tailormap/api/security/TailormapUserDetailsImpl.java
  src/main/java/org/tailormap/api/security/TailormapUserDetailsService.java
  src/test/java/org/tailormap/api/controller/UserControllerIntegrationTest.java
Labels: bug, breaking
