Repository Tailormap/tailormap-api, pull requests merged in 2025-04, with the labels that each got.

#1165 HTM-1447: Upgrade GeoTools to 33.0
  pom.xml
Labels: dependency

#1200 EK-44: Update drawing testdata in populate testdata
  src/main/java/org/tailormap/api/configuration/dev/PopulateTestData.java
  src/test/java/org/tailormap/api/controller/DrawingControllerIntegrationTest.java
Labels: enhancement

#1205 Bump io.fabric8:docker-maven-plugin from 0.45.1 to 0.46.0
  pom.xml
Labels: infrastructure

#1215 HTM-1483: Check if web mercator is available for WMTS hiDpiSubstituteLayer.
  src/main/java/org/tailormap/api/persistence/helper/ApplicationHelper.java
Labels: bug
